name: Real Drop Scanner

on:
  schedule:
    # Запуск каждые 30 минут (в 00 и 30 минут каждого часа)
    - cron: '0,20 * * * *'
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  run_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Разрешение на запись истории
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install selenium webdriver-manager requests

      - name: Run Script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHANNEL: ${{ secrets.TG_CHANNEL }}
        run: python main.py

      - name: Save History
        run: |
          git config user.name "DropBot"
          git config user.email "bot@drop.com"
          git add history.json
          git commit -m "Update match history" || echo "No changes"
          git push
